version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - cargo-cache-{{ checksum "Cargo.toml" }}
      #       - cargo-cache-
      # - run: cargo build
      # - run: cargo test
      # EU_GCR_API_KEY_JSON
      - setup_remote_docker
      - run: echo $EU_GCR_API_KEY_JSON | docker login -u _json_key --password-stdin https://eu.gcr.io
      # TODO: coverage https://abronan.com/building-a-rust-project-on-circleci/
      - run: docker build -t dom-5-status .

      # - save_cache:
      #     key: cargo-cache-{{ checksum "Cargo.toml" }}
      #     paths:
      #       - "~/.cargo"
      #       - "./target"
      #       - "/usr/local/cargo"

  deploy:
    docker:
      - image: circleci/python # just something small that includes ssh
    steps:
      - add_ssh_keys
      - run:
          name: SSH to server and deploy
          command: |
            ssh -o "StrictHostKeyChecking=no" \
                   "$SSH_ADDRESS" \
                   "docker exec \"$CONTAINER_ID\" bash -ec 'git pull; cargo install --force'; docker restart \"$CONTAINER_ID\""

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_approval:
          type: approval
          requires:
           - build
      - deploy:
          requires:
            - build
            - deploy_approval
          filters:
            branches:
              only: master
